//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XisfFileManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@\"E:\\Photography\\Astro Photography\\Processing\"")]
        public string Persist_FolderBrowseState {
            get {
                return ((string)(this["Persist_FolderBrowseState"]));
            }
            set {
                this["Persist_FolderBrowseState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@\"E:\\Photography\\Astro Photography\\Processing\"")]
        public string Persist_FolderCsvBrowseState {
            get {
                return ((string)(this["Persist_FolderCsvBrowseState"]));
            }
            set {
                this["Persist_FolderCsvBrowseState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public double Persist_FwhmPercentState {
            get {
                return ((double)(this["Persist_FwhmPercentState"]));
            }
            set {
                this["Persist_FwhmPercentState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double Persist_FwhmRangeHighState {
            get {
                return ((double)(this["Persist_FwhmRangeHighState"]));
            }
            set {
                this["Persist_FwhmRangeHighState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Persist_FwhmRangeLowState {
            get {
                return ((double)(this["Persist_FwhmRangeLowState"]));
            }
            set {
                this["Persist_FwhmRangeLowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public double Persist_EccentricityPercentState {
            get {
                return ((double)(this["Persist_EccentricityPercentState"]));
            }
            set {
                this["Persist_EccentricityPercentState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double Persist_EccentricityRangeHighState {
            get {
                return ((double)(this["Persist_EccentricityRangeHighState"]));
            }
            set {
                this["Persist_EccentricityRangeHighState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Persist_EccentricityRangeLowState {
            get {
                return ((double)(this["Persist_EccentricityRangeLowState"]));
            }
            set {
                this["Persist_EccentricityRangeLowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double Persist_SnrPercentState {
            get {
                return ((double)(this["Persist_SnrPercentState"]));
            }
            set {
                this["Persist_SnrPercentState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double Persist_SnrRangeHighState {
            get {
                return ((double)(this["Persist_SnrRangeHighState"]));
            }
            set {
                this["Persist_SnrRangeHighState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Persist_SnrRangeLowState {
            get {
                return ((double)(this["Persist_SnrRangeLowState"]));
            }
            set {
                this["Persist_SnrRangeLowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Persist_MedianPercentState {
            get {
                return ((double)(this["Persist_MedianPercentState"]));
            }
            set {
                this["Persist_MedianPercentState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double Persist_MedianRangeHighState {
            get {
                return ((double)(this["Persist_MedianRangeHighState"]));
            }
            set {
                this["Persist_MedianRangeHighState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Persist_MedianRangeLowState {
            get {
                return ((double)(this["Persist_MedianRangeLowState"]));
            }
            set {
                this["Persist_MedianRangeLowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Persist_MeanMedianDeviationPercentState {
            get {
                return ((double)(this["Persist_MeanMedianDeviationPercentState"]));
            }
            set {
                this["Persist_MeanMedianDeviationPercentState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double Persist_MeanMedianDeviationRangeHighState {
            get {
                return ((double)(this["Persist_MeanMedianDeviationRangeHighState"]));
            }
            set {
                this["Persist_MeanMedianDeviationRangeHighState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Persist_MeanMedianDeviationRangeLowState {
            get {
                return ((double)(this["Persist_MeanMedianDeviationRangeLowState"]));
            }
            set {
                this["Persist_MeanMedianDeviationRangeLowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Persist_NoisePercentState {
            get {
                return ((double)(this["Persist_NoisePercentState"]));
            }
            set {
                this["Persist_NoisePercentState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double Persist_NoiseRangeHighState {
            get {
                return ((double)(this["Persist_NoiseRangeHighState"]));
            }
            set {
                this["Persist_NoiseRangeHighState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Persist_NoiseRangeLowState {
            get {
                return ((double)(this["Persist_NoiseRangeLowState"]));
            }
            set {
                this["Persist_NoiseRangeLowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double Persist_UpdateStatisticsRangeHighState {
            get {
                return ((double)(this["Persist_UpdateStatisticsRangeHighState"]));
            }
            set {
                this["Persist_UpdateStatisticsRangeHighState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Persist_UpdateStatisticsRangeLowState {
            get {
                return ((double)(this["Persist_UpdateStatisticsRangeLowState"]));
            }
            set {
                this["Persist_UpdateStatisticsRangeLowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Persist_EccentricityMeanDeviationPercentState {
            get {
                return ((double)(this["Persist_EccentricityMeanDeviationPercentState"]));
            }
            set {
                this["Persist_EccentricityMeanDeviationPercentState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Persist_EccentricityMeanDeviationRangeLowState {
            get {
                return ((double)(this["Persist_EccentricityMeanDeviationRangeLowState"]));
            }
            set {
                this["Persist_EccentricityMeanDeviationRangeLowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double Persist_EccentricityMeanDeviationRangeHighState {
            get {
                return ((double)(this["Persist_EccentricityMeanDeviationRangeHighState"]));
            }
            set {
                this["Persist_EccentricityMeanDeviationRangeHighState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Persist_FwhmMeanDeviationPercentState {
            get {
                return ((double)(this["Persist_FwhmMeanDeviationPercentState"]));
            }
            set {
                this["Persist_FwhmMeanDeviationPercentState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double Persist_FwhmMeanDeviationRangeHighState {
            get {
                return ((double)(this["Persist_FwhmMeanDeviationRangeHighState"]));
            }
            set {
                this["Persist_FwhmMeanDeviationRangeHighState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Persist_FwhmMeanDeviationRangeLowState {
            get {
                return ((double)(this["Persist_FwhmMeanDeviationRangeLowState"]));
            }
            set {
                this["Persist_FwhmMeanDeviationRangeLowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Persist_NoiseRatioPercentState {
            get {
                return ((double)(this["Persist_NoiseRatioPercentState"]));
            }
            set {
                this["Persist_NoiseRatioPercentState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double Persist_NoiseRatioRangeHighState {
            get {
                return ((double)(this["Persist_NoiseRatioRangeHighState"]));
            }
            set {
                this["Persist_NoiseRatioRangeHighState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Persist_NoiseRatioRangeLowState {
            get {
                return ((double)(this["Persist_NoiseRatioRangeLowState"]));
            }
            set {
                this["Persist_NoiseRatioRangeLowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Persist_StarResidualMeanDevationPercentState {
            get {
                return ((double)(this["Persist_StarResidualMeanDevationPercentState"]));
            }
            set {
                this["Persist_StarResidualMeanDevationPercentState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double Persist_StarResidualMeanDevationRangeHighState {
            get {
                return ((double)(this["Persist_StarResidualMeanDevationRangeHighState"]));
            }
            set {
                this["Persist_StarResidualMeanDevationRangeHighState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Persist_StarResidualMeanDevationRangeLowState {
            get {
                return ((double)(this["Persist_StarResidualMeanDevationRangeLowState"]));
            }
            set {
                this["Persist_StarResidualMeanDevationRangeLowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Persist_StarResidualPercentState {
            get {
                return ((double)(this["Persist_StarResidualPercentState"]));
            }
            set {
                this["Persist_StarResidualPercentState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double Persist_StarResidualRangeHighState {
            get {
                return ((double)(this["Persist_StarResidualRangeHighState"]));
            }
            set {
                this["Persist_StarResidualRangeHighState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Persist_StarResidualRangeLowState {
            get {
                return ((double)(this["Persist_StarResidualRangeLowState"]));
            }
            set {
                this["Persist_StarResidualRangeLowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Persist_StarsPercentState {
            get {
                return ((double)(this["Persist_StarsPercentState"]));
            }
            set {
                this["Persist_StarsPercentState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double Persist_StarsRangeHighState {
            get {
                return ((double)(this["Persist_StarsRangeHighState"]));
            }
            set {
                this["Persist_StarsRangeHighState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Persist_StarsRangeLowState {
            get {
                return ((double)(this["Persist_StarsRangeLowState"]));
            }
            set {
                this["Persist_StarsRangeLowState"] = value;
            }
        }
    }
}
